sonar.projectKey=market-exchange-frontend
sonar.projectName=Market Exchange Frontend
sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.tests=src
sonar.test.inclusions=**/*.test.*,**/*.spec.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info